# NumPy

In [2]:
import numpy as np

creo il primo array (o lista). In NumPy le liste contengono oggetti di un solo tipo e possono cambiare "forma".

In [4]:
v1 = np.array([1,2,3,4,5,6,7,8,9])
v1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

creo una matrice: dati in due dimensioni

In [5]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
v1.shape

(9,)

In [7]:
m1.shape

(3, 3)

Provo a modificare la forma (shape) dei dati.

In [8]:
v2 = np.array([1,2,3,4,5,6,7,8,9])
print("primo shape: ", v2.shape)
v2.shape = (3,3)
print("nuovo shape: ", v2.shape)
v2


primo shape:  (9,)
nuovo shape:  (3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Accesso ai valori

In [9]:
v2[0,0]

1

In [11]:
print(v2[0][0])


1


In [12]:
v2[0,0] = 99
v2

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

Lo slicing funziona come per le liste di Python.

In [13]:
n = np.array([0,1,2,3,4,5,6,7,8,9])
print(n[2])
print("negativo",n[-1])
print("range",n[3:5])
print("da 5 a fine",n[5:])
print("da inizio a 5",n[:5])

2
negativo 9
range [3 4]
da 5 a fine [5 6 7 8 9]
da inizio a 5 [0 1 2 3 4]


Uso la matrice v2. Estraggo una riga.

In [17]:
print("matrice:\n", v2)
print("una riga", v2[1])

matrice:
 [[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]
una riga [4 5 6]


Estraggo una colonna da v2

In [19]:
print(v2[:,0]) #tutti gli elementi in riga con indice di colonna 0

[99  4  7]


Aggiungo e inserisco elementi

In [20]:
n = np.array([1,2,3,4,5])
n2 = np.append(n, 100)
n2

array([  1,   2,   3,   4,   5, 100])

In [21]:
n3 = np.insert(n, 3, 100) #lista, posizione, valore da inserire
print(n3)

[  1   2   3 100   4   5]


## Operazioni con oggetti numpy

In [23]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print("somma a+b:", a+b)
print("somma a-b:", a-b)
print("somma a*b:", a*b)

somma a+b: [11 22 33 44]
somma a-b: [ 9 18 27 36]
somma a*b: [ 10  40  90 160]


In [24]:
a*0.5

array([ 5., 10., 15., 20.])

In [25]:
a > 15

array([False,  True,  True,  True])

## Generare dati

In [26]:
#elenco di numeri
v = np.arange(1,10)
print(v, v.shape)

[1 2 3 4 5 6 7 8 9] (9,)


In [27]:
#numeri casuali
m = np.random.random((4,4))
print(m)

[[0.86082149 0.0558334  0.28504402 0.39901974]
 [0.7610213  0.53065547 0.25556959 0.6301549 ]
 [0.25169945 0.96898385 0.16015777 0.79824679]
 [0.34063532 0.09523715 0.26560878 0.55226404]]


In [28]:
m*100.0

array([[86.0821493 ,  5.58333999, 28.50440215, 39.90197395],
       [76.10212976, 53.06554696, 25.55695871, 63.01548964],
       [25.16994463, 96.89838484, 16.01577712, 79.82467903],
       [34.06353182,  9.52371492, 26.5608785 , 55.22640388]])

In [29]:
m2 = np.random.randint(0,100, (4,4))
print(m2)

[[62 13 40 66]
 [ 2 78 47 25]
 [26 14 91 39]
 [38 37 74 94]]


In [30]:
m3 = np.empty((3,3))
m3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
m4 = np.zeros((3,3))
m4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
m5 = np.ones((3,3))
m5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
m6 = np.full((3,3), 'hi!')
m6

array([['hi!', 'hi!', 'hi!'],
       ['hi!', 'hi!', 'hi!'],
       ['hi!', 'hi!', 'hi!']], dtype='<U3')

## Shuffle di una lista

In [36]:
lotto = np.arange(1,91)
print(lotto)
np.random.shuffle(lotto)
print(lotto)
print(lotto[:6])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]
[88 45 84 85 16  4 51 63 68 80 64 19 61 30 34 35 12 60  7 67 25 76 31 79
 10  6 36 48 15 58 38 70 71 18 47  9 87 28 27 50 17 40 77  1 66 86 75  5
 39 26 41 54 73 72 21 44 11 46  2 82 23 49 42 59 55 13 22 14 78 52 29  8
 65 37 24 69 89 33 53 74 62 56 83 32  3 90 20 81 57 43]
[88 45 84 85 16  4]
