# NumPy - parte 2

In [10]:
import numpy as np

Genero una lista di numeri casuali

In [11]:
n = np.random.randint(0,100, 20)
print(n)

[11 39 85  7 24 46 89 17 15 90 40  0 33 87 93 36 37 64 50 87]


Filtro gli elementi "al volo"

In [12]:
n2 = n[n < 50]
print(n2)

[11 39  7 24 46 17 15 40  0 33 36 37]


In [13]:
n3 = n[n != 7]
print(n3)

[11 39 85 24 46 89 17 15 90 40  0 33 87 93 36 37 64 50 87]


estraggo i numeri pari

In [14]:
npari = n[ n%2 == 0 ]
print(npari)

[24 46 90 40  0 36 64 50]


intervalli di numeri

In [15]:
n4 = n[(n >= 25) & (n <= 50) ] #and = &
print(n4)

[39 46 40 33 36 37 50]


In [16]:
n5 = n[(n<25) | (n>50)] # or = |
print(n5)

[11 85  7 24 89 17 15 90  0 87 93 64 87]


## where

In [18]:
n6 = np.where((n%2 == 0), "P", "D")
print(n6)

['D' 'D' 'D' 'D' 'P' 'P' 'D' 'D' 'D' 'P' 'P' 'P' 'D' 'D' 'D' 'P' 'D' 'P'
 'P' 'D']


# funzioni statistiche

In [20]:
print("min", np.amin(n))
print("max", np.amax(n))
print("media", np.average(n))
print("ptp", np.ptp(n))
print("sum", np.sum(n))

min 0
max 93
media 47.5
ptp 93
sum 950
